sudo: required
services:
 -docker
before_install:
 docker build -t vickyxce/react_test -f Dockerfile.dev . 
script:
 docker run -e CI=true vickyxce/react_test npm run test 
deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "react_test"
 env: "Reacttest-env"
 bucket_name: "elasticbeanstalk-ap-south-1-940902001939"
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: "$ACCESS_KEY"
 secret_access_key:
  secure: "$SECRET_KEY"
